/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FamilyMember = IDL.Record({
  'nom' : IDL.Text,
  'maladieY' : IDL.Bool,
  'maladies' : IDL.Text,
  'garantir' : IDL.Text,
  'stade' : IDL.Text,
  'dateNaissance' : IDL.Text,
  'formule' : IDL.Text,
  'antecedents' : IDL.Text,
});
export const Guarantee = IDL.Record({
  'service' : IDL.Text,
  'code' : IDL.Text,
  'risque' : IDL.Text,
  'intervention' : IDL.Text,
  'montant' : IDL.Nat,
  'pourcentage' : IDL.Nat,
});
export const Policy = IDL.Record({
  'statut' : IDL.Text,
  'type' : IDL.Text,
  'famille' : IDL.Vec(FamilyMember),
  'couverture' : IDL.Record({
    'maladiesGraves' : IDL.Nat,
    'hospitalisation' : IDL.Nat,
    'soinsAmbulatoires' : IDL.Nat,
  }),
  'garanties' : IDL.Vec(Guarantee),
  'numero' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addPolicy' : IDL.Func([IDL.Text, Policy], [], []),
  'getChatMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getFamilyMembers' : IDL.Func([IDL.Text], [IDL.Vec(FamilyMember)], ['query']),
  'getGuarantees' : IDL.Func([IDL.Text], [IDL.Vec(Guarantee)], ['query']),
  'getPolicyDetails' : IDL.Func([IDL.Text], [IDL.Opt(Policy)], ['query']),
  'initializePolicy' : IDL.Func([IDL.Text], [], []),
  'resetChatForUser' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func([IDL.Text], [Message], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FamilyMember = IDL.Record({
    'nom' : IDL.Text,
    'maladieY' : IDL.Bool,
    'maladies' : IDL.Text,
    'garantir' : IDL.Text,
    'stade' : IDL.Text,
    'dateNaissance' : IDL.Text,
    'formule' : IDL.Text,
    'antecedents' : IDL.Text,
  });
  const Guarantee = IDL.Record({
    'service' : IDL.Text,
    'code' : IDL.Text,
    'risque' : IDL.Text,
    'intervention' : IDL.Text,
    'montant' : IDL.Nat,
    'pourcentage' : IDL.Nat,
  });
  const Policy = IDL.Record({
    'statut' : IDL.Text,
    'type' : IDL.Text,
    'famille' : IDL.Vec(FamilyMember),
    'couverture' : IDL.Record({
      'maladiesGraves' : IDL.Nat,
      'hospitalisation' : IDL.Nat,
      'soinsAmbulatoires' : IDL.Nat,
    }),
    'garanties' : IDL.Vec(Guarantee),
    'numero' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addPolicy' : IDL.Func([IDL.Text, Policy], [], []),
    'getChatMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getFamilyMembers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(FamilyMember)],
        ['query'],
      ),
    'getGuarantees' : IDL.Func([IDL.Text], [IDL.Vec(Guarantee)], ['query']),
    'getPolicyDetails' : IDL.Func([IDL.Text], [IDL.Opt(Policy)], ['query']),
    'initializePolicy' : IDL.Func([IDL.Text], [], []),
    'resetChatForUser' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func([IDL.Text], [Message], []),
  });
};

export const init = ({ IDL }) => { return []; };