/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FamilyMember {
  'nom' : string,
  'maladieY' : boolean,
  'maladies' : string,
  'garantir' : string,
  'stade' : string,
  'dateNaissance' : string,
  'formule' : string,
  'antecedents' : string,
}
export interface Guarantee {
  'service' : string,
  'code' : string,
  'risque' : string,
  'intervention' : string,
  'montant' : bigint,
  'pourcentage' : bigint,
}
export interface Message {
  'id' : bigint,
  'content' : string,
  'role' : string,
  'timestamp' : bigint,
}
export interface Policy {
  'statut' : string,
  'type' : string,
  'famille' : Array<FamilyMember>,
  'couverture' : {
    'maladiesGraves' : bigint,
    'hospitalisation' : bigint,
    'soinsAmbulatoires' : bigint,
  },
  'garanties' : Array<Guarantee>,
  'numero' : string,
}
export interface _SERVICE {
  'addPolicy' : ActorMethod<[string, Policy], undefined>,
  'getChatMessages' : ActorMethod<[], Array<Message>>,
  'getFamilyMembers' : ActorMethod<[string], Array<FamilyMember>>,
  'getGuarantees' : ActorMethod<[string], Array<Guarantee>>,
  'getPolicyDetails' : ActorMethod<[string], [] | [Policy]>,
  'initializePolicy' : ActorMethod<[string], undefined>,
  'resetChatForUser' : ActorMethod<[Principal], undefined>,
  'sendMessage' : ActorMethod<[string], Message>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];